[
    {"key": "1", "value": "Alicante - ALC"},
    {"key": "2", "value": "Amsterdam - AMS"},
    {"key": "3", "value": "Athens - ATH"},
    {"key": "4", "value": "Auckland - AKL"},
    {"key": "5", "value": "Bangkok - BKK"},
    {"key": "6", "value": "Barcelona - BCN"},
    {"key": "7", "value": "Beijing - PEK"},
    {"key": "8", "value": "Berlin - BER"},
    {"key": "94", "value": "Beirut - BEY"},
    {"key": "9", "value": "Bilbao - BIO"},
    {"key": "10", "value": "Birmingham - BHX"},
    {"key": "100", "value": "Bogota - BOG"},
    {"key": "11", "value": "Bologna - BLQ"},
    {"key": "12", "value": "Bordeaux - BOD"},
    {"key": "13", "value": "Brasilia - GRU"},
    {"key": "14", "value": "Brisbane - BNE"},
    {"key": "15", "value": "Brussels - BRU"},
    {"key": "16", "value": "Budapest - BUD"},
    {"key": "17", "value": "Buenos Aires - EZE"},
    {"key": "18", "value": "Cairo - CAI"},
    {"key": "19", "value": "Catania - CTA"},
    {"key": "20", "value": "Chengdu - CTU"},
    {"key": "21", "value": "Chicago - ORD"},
    {"key": "22", "value": "Copenhagen - CPH"},
    {"key": "23", "value": "Cologne - CGN"},
    {"key": "24", "value": "Delhi - DEL"},
    {"key": "25", "value": "Dubai - DXB"},
    {"key": "26", "value": "Dublin - DUB"},
    {"key": "27", "value": "Düsseldorf - DUS"},
    {"key": "28", "value": "Edinburgh - EDI"},
    {"key": "29", "value": "Florence - FLR"},
    {"key": "30", "value": "Frankfurt - FRA"},
    {"key": "31", "value": "Fuerteventura - FUE"},
    {"key": "32", "value": "Geneva - GVA"},
    {"key": "33", "value": "Glasgow - GLA"},
    {"key": "34", "value": "Gran Canaria - LPA"},
    {"key": "35", "value": "Granada - GRX"},
    {"key": "36", "value": "Hamburg - HAM"},
    {"key": "99", "value": "Hanoi - HAN"},
    {"key": "37", "value": "Helsinki - HEL"},
    {"key": "38", "value": "Heraklion - HER"},
    {"key": "39", "value": "Hong Kong - HKG"},
    {"key": "40", "value": "Houston - IAH"},
    {"key": "41", "value": "Ibiza - IBZ"},
    {"key": "42", "value": "Istanbul - IST"},
    {"key": "95", "value": "Jakarta - CGK"},
    {"key": "43", "value": "Kuala Lumpur - KUL"},
    {"key": "96", "value": "Lagos - LOS"},
    {"key": "44", "value": "Lanzarote - ACE"},
    {"key": "45", "value": "Larnaca - LCA"},
    {"key": "98", "value": "Lima - LIM"},
    {"key": "46", "value": "Lisbon - LIS"},
    {"key": "47", "value": "London - LHR"},
    {"key": "48", "value": "Los Angeles - LAX"},
    {"key": "49", "value": "Lyon - LYS"},
    {"key": "50", "value": "Madrid - MAD"},
    {"key": "51", "value": "Malaga - AGP"},
    {"key": "52", "value": "Malta - MLA"},
    {"key": "53", "value": "Manchester - MAN"},
    {"key": "97", "value": "Manila - MNL"},
    {"key": "54", "value": "Marseille - MRS"},
    {"key": "55", "value": "Melbourne - MEL"},
    {"key": "56", "value": "Mexico City - MEX"},
    {"key": "57", "value": "Miami - MIA"},
    {"key": "58", "value": "Milan - MXP"},
    {"key": "59", "value": "Montreal - YUL"},
    {"key": "60", "value": "Moscow - SVO"},
    {"key": "61", "value": "Munich - MUC"},
    {"key": "62", "value": "Naples - NAP"},
    {"key": "63", "value": "New York - JFK"},
    {"key": "64", "value": "Nice - NCE"},
    {"key": "65", "value": "Ottawa - YYZ"},
    {"key": "66", "value": "Oslo - OSL"},
    {"key": "67", "value": "Palermo - PMO"},
    {"key": "68", "value": "Palma de Mallorca - PMI"},
    {"key": "69", "value": "Paris - CDG"},
    {"key": "70", "value": "Paphos - PFO"},
    {"key": "71", "value": "Prague - PRG"},
    {"key": "72", "value": "Reykjavik - KEF"},
    {"key": "73", "value": "Rome - FCO"},
    {"key": "74", "value": "San Francisco - SFO"},
    {"key": "75", "value": "Santiago de Compostela - SCQ"},
    {"key": "76", "value": "Seoul - ICN"},
    {"key": "77", "value": "Seville - SVQ"},
    {"key": "78", "value": "Shanghai - PVG"},
    {"key": "79", "value": "Singapore - SIN"},
    {"key": "80", "value": "Stockholm - ARN"},
    {"key": "81", "value": "Stuttgart - STR"},
    {"key": "82", "value": "Sydney - SYD"},
    {"key": "83", "value": "Thessaloniki - SKG"},
    {"key": "84", "value": "Tokyo - HND"},
    {"key": "85", "value": "Toronto - YYZ"},
    {"key": "86", "value": "Toulouse - TLS"},
    {"key": "87", "value": "Turin - TRN"},
    {"key": "88", "value": "Valencia - VLC"},
    {"key": "89", "value": "Venice - VCE"},
    {"key": "90", "value": "Verona - VRN"},
    {"key": "91", "value": "Vienna - VIE"},
    {"key": "92", "value": "Warsaw - WAW"},
    {"key": "93", "value": "Zurich - ZRH"}
]